<a href="https://colab.research.google.com/github/Fqlena/cienciadados/blob/main/Trabalho_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

arquivo = '/content/drive/MyDrive/Especialização/glicose_data_suja (1).csv'

data_frame = pd.read_csv(arquivo)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data_frame

,Dia Semana,Data,Antes Comer / Depois Comer,Resultado,Dose Insulina,kcal,carb,noite de sono,padel,musculacao R,musculacao H,pilates,corrida,caminhada,tenis,sauna,bike,natacao,eliptico,volei de areia
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-May,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sexta,2012.0,ac,96.0,6.0,2714.0,309.0,4,0.0,60.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Sábado,2012.0,ac,90.0,6.0,2665.0,334.0,4,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Domingo,2012.0,ac,105.0,6.0,2008.0,262.0,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Segunda,2012.0,ac,86.0,6.0,2117.0,291.0,5,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,Segunda,2014.0,ac,98.0,12.0,2626.0,157.0,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
721,Terça,2014.0,ac,92.0,12.0,2296.0,276.0,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
722,Quarta,2014.0,ac,91.0,12.0,2453.0,177.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
723,Quinta,2014.0,ac,99.0,12.0,2565.0,246.0,4,0.0,0.0,50.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0
724,Sexta,2014.0,ac,93.0,12.0,NaN,NaN,5,0.0,0.0,50.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
def categorizar_valor(valor):
    if valor <= 90:
        return 'baixo'
    elif valor <= 120:
        return 'normal'
    else:
        return 'alto'

data_frame['Resultado Categorizado'] = data_frame['Resultado'].apply(categorizar_valor)
#salvar no novo csv
#data_frame.to_csv('/content/drive/MyDrive/Especialização/glicose_data_suja_trabalho_novo.csv', index=False)
#print(data_frame[['Dia Semana', 'Resultado']][:10])

#exclui linhas que tem uma coluna com algum valor nulo
data_frame = data_frame.dropna(how='any')

In [ ]:
media_glicemia = data_frame['Resultado'].mean()
print(f"\nMedia Glicemia: {media_glicemia:.2f}")

Media Glicemia: 94.35

In [ ]:
mediana_glicemia = data_frame['Resultado'].median()
print(f"\nMediana Glicemia: {mediana_glicemia:.2f}")

Mediana Glicemia: 94.00

In [ ]:
media_kcal = data_frame['kcal'].mean()
print(f"\nMedia Kcal: {media_kcal:.2f}")

Media Kcal: 2411.70

In [ ]:
mediana_kcal = data_frame['kcal'].median()
print(f"\nMediana Kcal: {mediana_kcal:.2f}")

Mediana Kcal: 2377.00

In [ ]:
moda_glicemia = data_frame['Resultado'].mode()
print(f"\nModa Glicemia: {moda_glicemia}")

Moda Glicemia: 0    92.0
Name: Resultado, dtype: float64

In [ ]:
moda_kcal = data_frame['kcal'].mode()
print(f"\nModa Kcal: {moda_kcal}")

Moda Kcal: 0    2296.0
Name: kcal, dtype: float64

In [ ]:
media_glicemia = data_frame['Resultado'].mean()
mediana_glicemia = data_frame['Resultado'].median()
moda_glicemia = data_frame['Resultado'].mode()


media_kcal = data_frame['kcal'].mean()
mediana_kcal = data_frame['kcal'].median()
moda_kcal = data_frame['kcal'].mode()


moda_carb = data_frame['carb'].mode()
mediana_carb = data_frame['carb'].median()
moda_carb = data_frame['carb'].mode()


print(f"\nMedia Glicemia:\n{media_glicemia:.2f}")
print(f"\nMediana Glicemia:\n{mediana_glicemia:.2f}")
print(f"\nModa Glicemia:\n{moda_glicemia}")

print(f"\nMedia Kcal:\n{media_kcal:.2f}")
print(f"\nMediana Kcal:\n{mediana_kcal:.2f}")
print(f"\nModa Kcal:\n{moda_kcal}")

print(f"\nModa Kcal:\n{moda_kcal}")
print(f"\nMediana Carb:\n{mediana_carb:.2f}")
print(f"\nModa Carb:\n{moda_carb}")

Media Glicemia:
94.35

Mediana Glicemia:
94.00

Moda Glicemia:
0    92.0
Name: Resultado, dtype: float64

Media Kcal:
2411.70

Mediana Kcal:
2377.00

Moda Kcal:
0    2296.0
Name: kcal, dtype: float64

Moda Kcal:
0    2296.0
Name: kcal, dtype: float64

Mediana Carb:
251.00

Moda Carb:
0    209.0
1    251.0
2    267.0
3    271.0
Name: carb, dtype: float64

In [ ]:
media_glicemia = data_frame['Resultado'].mean()
mediana_glicemia = data_frame['Resultado'].median()
moda_glicemia = data_frame['Resultado'].mode()

media_kcal = data_frame['kcal'].mean()
mediana_kcal = data_frame['kcal'].median()
moda_kcal = data_frame['kcal'].mode()

moda_carb = data_frame['carb'].mode()
mediana_carb = data_frame['carb'].median()
moda_carb = data_frame['carb'].mode()

print(f"\nMedia Glicemia:\n{media_glicemia:.2f}")
print(f"\nMediana Glicemia:\n{mediana_glicemia:.2f}")
print(f"\nModa Glicemia:\n{moda_glicemia}")

print(f"\nMedia Kcal:\n{media_kcal:.2f}")
print(f"\nMediana Kcal:\n{mediana_kcal:.2f}")
print(f"\nModa Kcal:\n{moda_kcal}")

print(f"\nModa Kcal:\n{moda_kcal}")
print(f"\nMediana Carb:\n{mediana_carb:.2f}")
print(f"\nModa Carb:\n{moda_carb}")


contagem_valores_alto = data_f
print(f"\nContagem de dias com índice glicemico 'alto':  {contagem_valores_alto}")

Media Glicemia:
94.35

Mediana Glicemia:
94.00

Moda Glicemia:
0    92.0
Name: Resultado, dtype: float64

Media Kcal:
2411.70

Mediana Kcal:
2377.00

Moda Kcal:
0    2296.0
Name: kcal, dtype: float64

Moda Kcal:
0    2296.0
Name: kcal, dtype: float64

Mediana Carb:
251.00

Moda Carb:
0    209.0
1    251.0
2    267.0
3    271.0
Name: carb, dtype: float64

Contagem de dias com índice glicemico 'alto':  6